version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    restart: unless-stopped
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data/
  backend:
    image: ivanhom/kittygram_backend
    restart: unless-stopped
    env_file: .env
    volumes:
      - static:/backend_static/
      - media:/app/media/
    depends_on:
      - db
  frontend:
    image: ivanhom/kittygram_frontend
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static/
  gateway:
    image: ivanhom/kittygram_gateway
    restart: unless-stopped
    ports:
      - 9000:80
    volumes:
      - static:/staticfiles/
      - media:/media/
    depends_on:
      - backend
