version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    restart: on-failure
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data/
  backend:
    build: ./backend/
    restart: on-failure
    env_file: .env
    volumes:
      - static:/backend_static/
      - media:/app/media/
    depends_on:
      - db
  frontend:
    build: ./frontend/
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static/
  gateway:
    build: ./nginx/
    restart: on-failure
    ports:
      - 9000:80
    volumes:
      - static:/staticfiles/
      - media:/media/
    depends_on:
      - backend
